## thymeleaf start
## spring.thymeleaf.mode=HTML5
#spring.thymeleaf.mode=LEGACYHTML5
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.content-type=text/html
#spring.thymeleaf.cache=false
## thymeleaf end
server:
  port: 8081
  context-path: /
spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
mybatis:
  mapperLocations: classpath:mybatis/mappers/*.xml
  config-location: classpath:mybatis/mybatis-config.xml